package vn.edu.saigontech.SGTEnglishClub.Models;
// Generated Nov 4, 2018 2:51:43 PM by Hibernate Tools 5.1.10.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Files generated by hbm2java
 */
@Entity
@Table(name="files"
    ,catalog="sgt_englishclub"
)
public class Files  implements java.io.Serializable {


     private Integer id;
     private Materials materials;
     private String name;
     private boolean status;

    public Files() {
    }

    public Files(Materials materials, String name, boolean status) {
       this.materials = materials;
       this.name = name;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATERIAL_ID", nullable=false)
    public Materials getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Materials materials) {
        this.materials = materials;
    }

    
    @Column(name="NAME", nullable=false, length=1000)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="STATUS", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


